// Generated by formal/generate_sva.py from C/ACSL and available RTL metadata.
// requires -> assumptions; ensures -> assertions; assigns \nothing -> no memory interface.
// No claim about stability of combinational outputs while idle.
`timescale 1ns/1ps
module abs_acsl_sva (
    input wire clock,
    input wire reset,
    input wire start_port,
    input wire done_port,
    input wire [31:0] x,
    input wire [31:0] return_port
);
wire signed [63:0] acsl_x = {{32{x[31]}}, x};
wire signed [63:0] acsl_result = {{32{return_port[31]}}, return_port};
// requires[0]: x > -2147483648
wire requires_0 = (acsl_x > (-64'sd2147483648));
// ensures[0]: \result >= 0
wire ensures_0 = (acsl_result >= 64'sd0);
// ensures[1]: (x >= 0 ==> \result == x) && (x < 0 ==> \result == -x)
wire ensures_1 = ((!((acsl_x >= 64'sd0)) || ((acsl_result == acsl_x))) && (!((acsl_x < 64'sd0)) || ((acsl_result == (-acsl_x)))));
wire contract_domain = requires_0;
wire transaction_witness = reset && start_port && done_port && contract_domain;
// Yosys immediate form uses the SAME predicates as the concurrent SVA.
`ifdef YOSYS
always @* begin
    if (reset && start_port) requires_0_assume: assume (requires_0);
    if (reset) handshake_assert: assert (done_port == start_port);
    if (reset && done_port) ensures_0_assert: assert (ensures_0);
    if (reset && done_port) ensures_1_assert: assert (ensures_1);
    transaction_cover: cover (transaction_witness);
end
`else
requires_0_assume: assume property (@(posedge clock) disable iff (!reset)
    start_port |-> requires_0);
handshake_assert: assert property (@(posedge clock) disable iff (!reset)
    done_port == start_port);
ensures_0_assert: assert property (@(posedge clock) disable iff (!reset)
    done_port |-> ensures_0);
ensures_1_assert: assert property (@(posedge clock) disable iff (!reset)
    done_port |-> ensures_1);
transaction_cover: cover property (@(posedge clock) transaction_witness);
`endif
endmodule
