// Generated by formal/generate_sva.py from C/ACSL and available RTL metadata.
// requires -> assumptions; ensures -> assertions; assigns \nothing -> no memory interface.
// No claim about stability of combinational outputs while idle.
`timescale 1ns/1ps
module add_acsl_sva (
    input wire clock,
    input wire reset,
    input wire start_port,
    input wire done_port,
    input wire [31:0] x,
    input wire [31:0] y,
    input wire [31:0] return_port
);
wire signed [63:0] acsl_x = {{32{x[31]}}, x};
wire signed [63:0] acsl_y = {{32{y[31]}}, y};
wire signed [63:0] acsl_result = {{32{return_port[31]}}, return_port};
// requires[0]: x >= 0 && y >= 0
wire requires_0 = ((acsl_x >= 64'sd0) && (acsl_y >= 64'sd0));
// requires[1]: x + y <= 2147483647
wire requires_1 = ((acsl_x + acsl_y) <= 64'sd2147483647);
// ensures[0]: \result == x + y
wire ensures_0 = (acsl_result == (acsl_x + acsl_y));
wire contract_domain = requires_0 && requires_1;
wire transaction_witness = reset && start_port && done_port && contract_domain;
// Yosys immediate form uses the SAME predicates as the concurrent SVA.
`ifdef YOSYS
always @* begin
    if (reset && start_port) requires_0_assume: assume (requires_0);
    if (reset && start_port) requires_1_assume: assume (requires_1);
    if (reset) handshake_assert: assert (done_port == start_port);
    if (reset && done_port) ensures_0_assert: assert (ensures_0);
    transaction_cover: cover (transaction_witness);
end
`else
requires_0_assume: assume property (@(posedge clock) disable iff (!reset)
    start_port |-> requires_0);
requires_1_assume: assume property (@(posedge clock) disable iff (!reset)
    start_port |-> requires_1);
handshake_assert: assert property (@(posedge clock) disable iff (!reset)
    done_port == start_port);
ensures_0_assert: assert property (@(posedge clock) disable iff (!reset)
    done_port |-> ensures_0);
transaction_cover: cover property (@(posedge clock) transaction_witness);
`endif
endmodule
