// Generated by formal/generate_sva.py from C/ACSL and available RTL metadata.
// requires -> assumptions; ensures -> assertions; assigns \nothing -> no memory interface.
// No claim about stability of combinational outputs while idle.
`timescale 1ns/1ps
module min_acsl_sva (
    input wire clock,
    input wire reset,
    input wire start_port,
    input wire done_port,
    input wire [31:0] a,
    input wire [31:0] b,
    input wire [31:0] return_port
);
wire signed [63:0] acsl_a = {{32{a[31]}}, a};
wire signed [63:0] acsl_b = {{32{b[31]}}, b};
wire signed [63:0] acsl_result = {{32{return_port[31]}}, return_port};
// ensures[0]: \result <= a && \result <= b
wire ensures_0 = ((acsl_result <= acsl_a) && (acsl_result <= acsl_b));
// ensures[1]: \result == a || \result == b
wire ensures_1 = ((acsl_result == acsl_a) || (acsl_result == acsl_b));
wire contract_domain = 1'b1;
wire transaction_witness = reset && start_port && done_port && contract_domain;
// Yosys immediate form uses the SAME predicates as the concurrent SVA.
`ifdef YOSYS
always @* begin
    if (reset) handshake_assert: assert (done_port == start_port);
    if (reset && done_port) ensures_0_assert: assert (ensures_0);
    if (reset && done_port) ensures_1_assert: assert (ensures_1);
    transaction_cover: cover (transaction_witness);
end
`else
handshake_assert: assert property (@(posedge clock) disable iff (!reset)
    done_port == start_port);
ensures_0_assert: assert property (@(posedge clock) disable iff (!reset)
    done_port |-> ensures_0);
ensures_1_assert: assert property (@(posedge clock) disable iff (!reset)
    done_port |-> ensures_1);
transaction_cover: cover property (@(posedge clock) transaction_witness);
`endif
endmodule
