// Generated by formal/generate_sva.py from C/ACSL and available RTL metadata.
// requires -> assumptions; ensures -> assertions; assigns \nothing -> no memory interface.
// No claim about stability of combinational outputs while idle.
`timescale 1ns/1ps
module sign_acsl_sva (
    input wire clock,
    input wire contract_valid,
    input wire [31:0] x,
    input wire [31:0] result_value
);
// CONTRACT ONLY: clock/contract_valid/result_value are checker inputs,
// not inferred DUT ports. No bind or hardware proof until RTL + metadata exist.
wire signed [63:0] acsl_x = {{32{x[31]}}, x};
wire signed [63:0] acsl_result = {{32{result_value[31]}}, result_value};
// ensures[0]: (x > 0 ==> \result == 1) && (x < 0 ==> \result == -1) && (x == 0 ==> \result == 0)
wire ensures_0 = (((!((acsl_x > 64'sd0)) || ((acsl_result == 64'sd1))) && (!((acsl_x < 64'sd0)) || ((acsl_result == (-64'sd1))))) && (!((acsl_x == 64'sd0)) || ((acsl_result == 64'sd0))));
wire contract_domain = 1'b1;
wire transaction_witness = 1'b1 && contract_valid && contract_valid && contract_domain;
// Yosys immediate form uses the SAME predicates as the concurrent SVA.
`ifdef YOSYS
always @* begin
    if (1'b1 && contract_valid) ensures_0_assert: assert (ensures_0);
    transaction_cover: cover (transaction_witness);
end
`else
ensures_0_assert: assert property (@(posedge clock)
    contract_valid |-> ensures_0);
transaction_cover: cover property (@(posedge clock) transaction_witness);
`endif
endmodule
