#!/usr/bin/env python3
"""Translate the repository's scalar ACSL contracts; never edit source inputs.

This intentionally supports only the operators and 32-bit int signatures used
by these benchmarks. Unsupported syntax or inconsistent metadata is an error.
"""
import hashlib
import json
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from metadata_extractor import extract_metadata, parse_acsl_contract, parse_c_signature

TOKEN = re.compile(r"\s*(\\result|==>|&&|\|\||>=|<=|==|!=|[()+\-<>!]|[A-Za-z_]\w*|\d+)")
PRECEDENCE = {'==>': 1, '||': 2, '&&': 3, '==': 4, '!=': 4,
              '>': 5, '<': 5, '>=': 5, '<=': 5, '+': 6, '-': 6}


class Expression:
    def __init__(self, text, names):
        self.tokens, self.names, self.pos = [], names, 0
        remaining = text.strip()
        while remaining:
            match = TOKEN.match(remaining)
            if not match:
                raise ValueError(f'unsupported ACSL syntax: {remaining!r}')
            self.tokens.append(match.group(1))
            remaining = remaining[match.end():]

    def take(self):
        if self.pos == len(self.tokens):
            raise ValueError('incomplete ACSL expression')
        token = self.tokens[self.pos]
        self.pos += 1
        return token

    def parse(self, minimum=1):
        token = self.take()
        if token == '(':
            left = self.parse()
            if self.take() != ')':
                raise ValueError('unbalanced parentheses')
        elif token in ('-', '!', '+'):
            left = f'({token}{self.parse(7)})'
        elif token.isdigit():
            if int(token) > 2147483648:
                raise ValueError('integer constant outside supported range')
            left = f"64'sd{token}"
        elif token in self.names:
            left = self.names[token]
        else:
            raise ValueError(f'unknown ACSL name: {token}')
        while self.pos < len(self.tokens):
            op = self.tokens[self.pos]
            priority = PRECEDENCE.get(op, 0)
            if priority < minimum:
                break
            self.pos += 1
            right = self.parse(priority if op == '==>' else priority + 1)
            left = f'(!({left}) || ({right}))' if op == '==>' else f'({left} {op} {right})'
        return left

    def translate(self):
        result = self.parse()
        if self.pos != len(self.tokens):
            raise ValueError('trailing ACSL tokens')
        return result


def generate(name):
    source = ROOT / 'benchmarks' / f'{name}.c'
    contract = parse_acsl_contract(source)
    sig = parse_c_signature(source, name)
    if sig['return_type'] != 'int' or any(t != 'int' for t, _ in sig['parameters']):
        raise ValueError('only signed 32-bit int scalars are supported')
    if contract['assigns'] != [r'\nothing']:
        raise ValueError('memory side effects are unsupported')
    meta_path = ROOT / 'metadata' / f'{name}.meta.json'
    integrated = meta_path.exists() and (ROOT / f'{name}.v').exists()
    meta = None
    if integrated:
        meta = json.loads(meta_path.read_text())
        actual = extract_metadata(name)
        for key in ('function', 'source_file', 'rtl_file', 'top_module', 'contract',
                    'clock_reset', 'handshake', 'parameters', 'return', 'memory'):
            if meta[key] != actual[key]:
                raise ValueError(f'{name}: stale metadata field {key}')
        if meta['timing']['fixed_cycles'] != 0 or actual['timing']['fixed_cycles'] != 0:
            raise ValueError('only confirmed zero-cycle designs are supported')
        if meta['clock_reset'] != {'clock': 'clock', 'reset': 'reset', 'reset_polarity': 'active_low'}:
            raise ValueError('unsupported clock/reset mapping')
        if meta['handshake'] != {'protocol': 'start_done', 'start': 'start_port', 'done': 'done_port'}:
            raise ValueError('unsupported handshake')
        params = [(p['c_name'], p['rtl_port']) for p in meta['parameters']]
        result_port = meta['return']['rtl_port']
    else:
        params = [(p, p) for _, p in sig['parameters']]
        result_port = 'result_value'

    ports = ['input wire clock']
    ports += ['input wire reset', 'input wire start_port', 'input wire done_port'] if integrated else ['input wire contract_valid']
    ports += [f'input wire [31:0] {p}' for _, p in params]
    ports += [f'input wire [31:0] {result_port}']
    lines = ['// Generated by formal/generate_sva.py from C/ACSL and available RTL metadata.',
             '// requires -> assumptions; ensures -> assertions; assigns \\nothing -> no memory interface.',
             '// No claim about stability of combinational outputs while idle.',
             '`timescale 1ns/1ps', f'module {name}_acsl_sva (', '    ' + ',\n    '.join(ports), ');']
    if not integrated:
        lines += ['// CONTRACT ONLY: clock/contract_valid/result_value are checker inputs,',
                  '// not inferred DUT ports. No bind or hardware proof until RTL + metadata exist.']
    names = {}
    for c_name, port in params + [(r'\result', result_port)]:
        symbol = 'acsl_result' if c_name == r'\result' else f'acsl_{c_name}'
        names[c_name] = symbol
        lines += [f'wire signed [63:0] {symbol} = {{{{32{{{port}[31]}}}}, {port}}};']
    for keyword in ('requires', 'ensures'):
        for index, clause in enumerate(contract[keyword]):
            lines += [f'// {keyword}[{index}]: {clause}',
                      f'wire {keyword}_{index} = {Expression(clause, names).translate()};']
    enabled = 'reset' if integrated else "1'b1"
    launch = 'start_port' if integrated else 'contract_valid'
    valid = 'done_port' if integrated else 'contract_valid'
    pre = ' && '.join(f'requires_{i}' for i in range(len(contract['requires']))) or "1'b1"
    lines += [f'wire contract_domain = {pre};',
              f'wire transaction_witness = {enabled} && {launch} && {valid} && contract_domain;',
              '// Yosys immediate form uses the SAME predicates as the concurrent SVA.', '`ifdef YOSYS', 'always @* begin']
    for i in range(len(contract['requires'])):
        lines += [f'    if ({enabled} && {launch}) requires_{i}_assume: assume (requires_{i});']
    if integrated:
        lines += ['    if (reset) handshake_assert: assert (done_port == start_port);']
    for i in range(len(contract['ensures'])):
        lines += [f'    if ({enabled} && {valid}) ensures_{i}_assert: assert (ensures_{i});']
    lines += ['    transaction_cover: cover (transaction_witness);', 'end', '`else']
    disable = ' disable iff (!reset)' if integrated else ''
    for i in range(len(contract['requires'])):
        lines += [f'requires_{i}_assume: assume property (@(posedge clock){disable}', f'    {launch} |-> requires_{i});']
    if integrated:
        lines += ['handshake_assert: assert property (@(posedge clock) disable iff (!reset)', '    done_port == start_port);']
    for i in range(len(contract['ensures'])):
        lines += [f'ensures_{i}_assert: assert property (@(posedge clock){disable}', f'    {valid} |-> ensures_{i});']
    lines += ['transaction_cover: cover property (@(posedge clock) transaction_witness);', '`endif', 'endmodule', '']
    (ROOT / 'sva' / f'{name}_acsl.sv').write_text('\n'.join(lines))

    if integrated:
        module = ('\\' + meta['top_module']['verilog_name'] + ' ') if meta['top_module']['escaped'] else meta['top_module']['verilog_name']
        signals = ['clock', 'reset', 'start_port', 'done_port'] + [p for _, p in params] + [result_port]
        connections = ', '.join(f'.{p}({p})' for p in signals)
        (ROOT / 'sva' / f'{name}_bind.sv').write_text(
            '// Compile with the original RTL and corresponding checker.\n'
            f'bind {module} {name}_acsl_sva acsl_checker ({connections});\n')
        top_ports = ['input wire clock', 'input wire reset', 'input wire start_port'] + [f'input wire [31:0] {p}' for _, p in params]
        harness = ['`timescale 1ns/1ps', f'module {name}_formal (', '    ' + ',\n    '.join(top_ports), ');',
                   'wire done_port;', f'wire [31:0] {result_port};', f'{module} dut ({connections});',
                   f'{name}_acsl_sva acsl_checker ({connections});', 'endmodule', '']
        (ROOT / 'formal' / f'{name}_formal.sv').write_text('\n'.join(harness))
    files = [source] + ([ROOT / f'{name}.v', meta_path] if integrated else [])
    return {'function': name, 'status': 'ready' if integrated else 'pending_rtl_and_metadata',
            'requires': contract['requires'], 'ensures': contract['ensures'],
            'assigns': contract['assigns'], 'assertion_count': len(contract['ensures']) + int(integrated),
            'inputs_sha256': {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest() for p in files}}


def main():
    (ROOT / 'sva').mkdir(exist_ok=True)
    records = [generate(p.stem) for p in sorted((ROOT / 'benchmarks').glob('*.c'))]
    (ROOT / 'formal' / 'translation_manifest.json').write_text(json.dumps(records, indent=2) + '\n')
    for record in records:
        print(f"{record['function']}: {record['status']}; {len(record['ensures'])} postconditions")


if __name__ == '__main__':
    main()
